In [55]:
import pandas as pd

In [56]:
from IPython.display import display, HTML

display(HTML("""
<style>
    table.dataframe td {
        white-space: nowrap;
    }
</style>
"""))

In [57]:
df_crashes = pd.read_csv("../data/traffic_crashes/traffic_crashes.csv")

In [58]:
print(df_crashes.shape)
df_crashes.head()

(1000, 49)

,crash_record_id,rd_no,crash_date_est_i,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,...,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,location
0,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,...,0.0,0.0,2.0,0.0,14,6,12,41.794850,-87.767280,POINT (-87.767280356289 41.794849958048)
1,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,...,0.0,0.0,2.0,0.0,14,6,12,41.881271,-87.686536,POINT (-87.686535940171 41.881270504288)
2,444221c2a9bc82fc4f301062ab22b482d7d661cf88fcdf...,JE494016,Y,2021-12-31T13:56:00.000,10,OTHER,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,...,0.0,0.0,2.0,0.0,13,6,12,41.722941,-87.662863,POINT (-87.662862871273 41.72294121821)
3,4603435fbb4ef5d45c0d805c3e9aa5558a311a140a737e...,JE494049,NaN,2021-12-31T13:46:00.000,30,NO CONTROLS,NO CONTROLS,RAIN,DAYLIGHT,PEDALCYCLIST,...,1.0,0.0,2.0,0.0,13,6,12,41.766336,-87.578270,POINT (-87.578269718478 41.766335621716)
4,db62bb4534d0dae57112ea3ff8d50193784aaa732ed58d...,JE494000,NaN,2021-12-31T13:45:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,...,0.0,0.0,2.0,0.0,13,6,12,41.751150,-87.607802,POINT (-87.607802036151 41.7511501753)

In [59]:
df_crashes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 49 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   crash_record_id                1000 non-null   object
 1   rd_no                          1000 non-null   object
 2   crash_date_est_i               69 non-null     object
 3   crash_date                     1000 non-null   object
 4   posted_speed_limit             1000 non-null   int64
 5   traffic_control_device         1000 non-null   object
 6   device_condition               1000 non-null   object
 7   weather_condition              1000 non-null   object
 8   lighting_condition             1000 non-null   object
 9   first_crash_type               1000 non-null   object
 10  trafficway_type                1000 non-null   object
 11  lane_cnt                       1 non-null      float64
 12  alignment                      1000 non-null   object
 13  roadway_surface_cond           1000 non-null   object
 14  road_defect                    1000 non-null   object
 15  report_type                    976 non-null    object
 16  crash_type                     1000 non-null   object
 17  intersection_related_i         271 non-null    object
 18  private_property_i             45 non-null     object
 19  hit_and_run_i                  320 non-null    object
 20  damage                         1000 non-null   object
 21  date_police_notified           1000 non-null   object
 22  prim_contributory_cause        1000 non-null   object
 23  sec_contributory_cause         1000 non-null   object
 24  street_no                      1000 non-null   int64
 25  street_direction               1000 non-null   object
 26  street_name                    1000 non-null   object
 27  beat_of_occurrence             1000 non-null   int64
 28  photos_taken_i                 15 non-null     object
 29  statements_taken_i             22 non-null     object
 30  dooring_i                      0 non-null      float64
 31  work_zone_i                    4 non-null      object
 32  work_zone_type                 3 non-null      object
 33  workers_present_i              1 non-null      object
 34  num_units                      1000 non-null   int64
 35  most_severe_injury             998 non-null    object
 36  injuries_total                 998 non-null    float64
 37  injuries_fatal                 998 non-null    float64
 38  injuries_incapacitating        998 non-null    float64
 39  injuries_non_incapacitating    998 non-null    float64
 40  injuries_reported_not_evident  998 non-null    float64
 41  injuries_no_indication         998 non-null    float64
 42  injuries_unknown               998 non-null    float64
 43  crash_hour                     1000 non-null   int64
 44  crash_day_of_week              1000 non-null   int64
 45  crash_month                    1000 non-null   int64
 46  latitude                       987 non-null    float64
 47  longitude                      987 non-null    float64
 48  location                       987 non-null    object
dtypes: float64(11), int64(7), object(31)
memory usage: 382.9+ KB

In [60]:
df_crashes.isnull().sum()

crash_record_id                     0
rd_no                               0
crash_date_est_i                  931
crash_date                          0
posted_speed_limit                  0
traffic_control_device              0
device_condition                    0
weather_condition                   0
lighting_condition                  0
first_crash_type                    0
trafficway_type                     0
lane_cnt                          999
alignment                           0
roadway_surface_cond                0
road_defect                         0
report_type                        24
crash_type                          0
intersection_related_i            729
private_property_i                955
hit_and_run_i                     680
damage                              0
date_police_notified                0
prim_contributory_cause             0
sec_contributory_cause              0
street_no                           0
street_direction                    0
street_name                         0
beat_of_occurrence                  0
photos_taken_i                    985
statements_taken_i                978
dooring_i                        1000
work_zone_i                       996
work_zone_type                    997
workers_present_i                 999
num_units                           0
most_severe_injury                  2
injuries_total                      2
injuries_fatal                      2
injuries_incapacitating             2
injuries_non_incapacitating         2
injuries_reported_not_evident       2
injuries_no_indication              2
injuries_unknown                    2
crash_hour                          0
crash_day_of_week                   0
crash_month                         0
latitude                           13
longitude                          13
location                           13
dtype: int64

In [61]:
df_crashes = df_crashes.dropna(axis="columns", how="all")
df_crashes.shape

(1000, 48)

In [62]:
df_crashes = df_crashes.dropna(axis="index", thresh=2)
df_crashes.shape

(1000, 48)

In [63]:
df_crashes.report_type.unique()

array(['ON SCENE', 'NOT ON SCENE (DESK REPORT)', nan], dtype=object)

In [64]:
df_crashes = df_crashes.fillna(value={"report_type": "ON SCENE"})

In [66]:
df_crashes.report_type.unique()

array(['ON SCENE', 'NOT ON SCENE (DESK REPORT)'], dtype=object)

In [67]:
df_vehicles = pd.read_csv("../data/traffic_crashes/traffic_crash_vehicle.csv")
df_vehicles.head()

,crash_unit_id,crash_record_id,rd_no,crash_date,unit_no,unit_type,num_passengers,vehicle_id,cmrc_veh_i,make,...,trailer1_length,trailer2_length,total_vehicle_length,axle_cnt,vehicle_config,cargo_body_type,load_type,hazmat_out_of_service_i,mcs_out_of_service_i,hazmat_class
0,1255349,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,2021-12-31T14:00:00.000,1,DRIVER,NaN,1191605.0,NaN,DODGE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1255350,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,2021-12-31T14:00:00.000,2,DRIVER,NaN,1191608.0,NaN,KIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1255351,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,2021-12-31T14:00:00.000,3,PARKED,NaN,1191614.0,NaN,CHRYSLER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1255367,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,2021-12-31T14:00:00.000,1,DRIVER,NaN,1191620.0,NaN,TOYOTA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1255368,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,2021-12-31T14:00:00.000,2,DRIVER,NaN,1191622.0,NaN,GENERAL MOTORS CORPORATION (GMC),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df = df_crashes.merge(df_vehicles, how="left", on="crash_record_id", suffixes=("_left", "_right"))
df.head()

,crash_record_id,rd_no_left,crash_date_est_i,crash_date_left,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,...,trailer1_length,trailer2_length,total_vehicle_length,axle_cnt,vehicle_config,cargo_body_type,load_type,hazmat_out_of_service_i,mcs_out_of_service_i,hazmat_class
0,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
df_agg = df.groupby("vehicle_type").agg(({"crash_record_id": "count"})).reset_index()

In [77]:
number_of_passengers_cars_involved = df_agg[df_agg["vehicle_type"] == "PASSENGER"].crash_record_id.array[0]
number_of_passengers_cars_involved

np.int64(633)